server:
  port: 8082
spring:
  resources:
    static-locations: classpath:/
  datasource:
    dynamic:
      primary: master #设置默认的数据源或者数据源组,默认值即为master
      strict: false #严格匹配数据源,默认false. true未匹配到指定数据源时抛异常,false使用默认数据源
      datasource:
        master:
          url: jdbc:mysql://10.54.37.81:13306/dwd_330100?useUnicode=true&characterEncoding=UTF-8&relaxAutoCommit=true&useSSL=false&rewriteBatchedStatements=true
          username: sfzcrds_user
          password: jtzlzxAAA1
          driver-class-name: com.mysql.jdbc.Driver # 3.2.0开始支持SPI可省略此配置
          lazy: true
        local:
          url: jdbc:mysql://127.0.0.1:3306/traffic_test?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&rewriteBatchedStatements=true
          username: root
          password: wasd62300
          driver-class-name: com.mysql.jdbc.Driver
          lazy: true
        pg:
          url: jdbc:postgresql://127.0.0.1:5432/postgres?useUnicode=true&characterEncoding=UTF-8&relaxAutoCommit=true&useSSL=false
          username: postgres
          password: 123456
          driver-class-name: org.postgresql.Driver # 3.2.0开始支持SPI可省略此配置
          lazy: true
        odps:
          url: jdbc:odps:http://service.cn-hangzhou-hzegc-d01.odps.ops.hzegcv3.cn/api?project=odps_hzsjtysj
          username: nalVftZFovXIPPu2
          password: I9EnkBrbzZVJUyWij0kmQLbTxnGBOu
          driver-class-name: com.aliyun.odps.jdbc.OdpsDriver
          lazy: true
        # 中控RDS
        zk_rds:
          url: jdbc:mysql://10.54.37.81:13306/dws_330100?useUnicode=true&characterEncoding=UTF-8&relaxAutoCommit=true&useSSL=false
          username: sfzcrds_user
          password: jtzlzxAAA1
          driver-class-name: com.mysql.jdbc.Driver
          lazy: true
forest:
  backend: okhttp3             # 后端HTTP框架（默认为 okhttp3）
  max-connections: 1000        # 连接池最大连接数（默认为 500）
  max-route-connections: 500   # 每个路由的最大连接数（默认为 500）
  max-request-queue-size: 100  # [自v1.5.22版本起可用] 最大请求等待队列大小
  max-async-thread-size: 300   # [自v1.5.21版本起可用] 最大异步线程数
  max-async-queue-size: 16     # [自v1.5.22版本起可用] 最大异步线程池队列大小
  timeout: 70000                # [已不推荐使用] 请求超时时间，单位为毫秒（默认为 3000）
  connect-timeout: 70000        # 连接超时时间，单位为毫秒（默认为 timeout）
  read-timeout: 70000          # 数据读取超时时间，单位为毫秒（默认为 timeout）
  max-retry-count: 1           # 请求失败后重试次数（默认为 0 次不重试）
  ssl-protocol: TLS            # 单向验证的HTTPS的默认TLS协议（默认为 TLS）
  log-enabled: true            # 打开或关闭日志（默认为 true）
  log-request: true            # 打开/关闭Forest请求日志（默认为 true）
  log-response-status: true    # 打开/关闭Forest响应状态日志（默认为 true）
  log-response-content: true   # 打开/关闭Forest响应内容日志（默认为 false）
  async-mode: platform         # [自v1.5.27版本起可用] 异步模式（默认为 platform）


