server:
  port: 8082
spring:
  resources:
    static-locations: classpath:/
  datasource:
    dynamic:
      primary: master #设置默认的数据源或者数据源组,默认值即为master
      strict: false #严格匹配数据源,默认false. true未匹配到指定数据源时抛异常,false使用默认数据源
      datasource:
        master:
          url: jdbc:postgresql://127.0.0.1:5432/postgres?useUnicode=true&characterEncoding=UTF-8&relaxAutoCommit=true&useSSL=false
          username: postgres
          password: 123456
          driver-class-name: org.postgresql.Driver # 3.2.0开始支持SPI可省略此配置
        odps:
          url: jdbc:odps:http://service.cn-hangzhou-hzegc-d01.odps.cloud.hzegcv3.cn/api?project=odps_hzsjtysj
          username: nalVftZFovXIPPu2
          password: I9EnkBrbzZVJUyWij0kmQLbTxnGBOu
          driver-class-name: com.aliyun.odps.jdbc.OdpsDriver
          lazy: true
