package com.traffic.service.impl;

import com.baomidou.mybatisplus.extension.service.impl.ServiceImpl;
import com.traffic.entity.DwdTfcRltnWideDsecroadCameraInfoCopy;
import com.traffic.mapper.DwdTfcRltnWideDsecroadCameraInfoCopyMapper;
import com.traffic.service.DwdTfcRltnWideDsecroadCameraInfoCopyService;
import org.springframework.stereotype.Service;

@Service
public class DwdTfcRltnWideDsecroadCameraInfoCopyServiceImpl extends ServiceImpl<DwdTfcRltnWideDsecroadCameraInfoCopyMapper, DwdTfcRltnWideDsecroadCameraInfoCopy> implements DwdTfcRltnWideDsecroadCameraInfoCopyService {
}
